# ===============================
# LOG LEVEL
# ===============================

logging.level.root=INFO
logging.level.com.example.baitap03_ss09=DEBUG

# ===============================
# CONSOLE FORMAT
# ===============================

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%level] %logger{36} - %msg%n

# ===============================
# FILE FORMAT
# ===============================

logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%level] %logger{36} - %msg%n

# ===============================
# FILE LOG
# ===============================

logging.file.path=logs